title = "Factual Audio"
languageCode = "en"

theme = "ghostwriter"
copyright = "Etienne Dechamps"

[Author]
name = "Etienne Dechamps"
email = "etienne@edechamps.fr"
# TODO: ideally this should honor baseURL, but it's not clear how to do that cleanly.
profile = "https://factualaudio.com/page/about/"

[Params]
intro = true
headline = "Factual Audio"
description = "The knowledge base for home audio enthusiasts"
facebook = "https://www.facebook.com/FactualAudio/"
twitter = "https://twitter.com/FactualAudio"
shareGooglePlus = false
jqueryURL = "https://code.jquery.com/jquery-3.2.1.slim.js"
bigfootURL = "https://cdn.rawgit.com/lemonmade/bigfoot/2.1.4"

[Outputs]
home = ["HTML", "RSS"]
