title = "Factual Audio"
languageCode = "en-gb"

theme = "ghostwriter"
copyright = "Etienne Dechamps"

[Author]
name = "Etienne Dechamps"
email = "etienne@edechamps.fr"

[Params]
intro = true
headline = "Factual Audio"
description = "The knowledge base for home audio enthusiasts"

[[menu.main]]
name = "About"
url = "/page/about/"
