title = "Factual Audio"
languageCode = "en-gb"

theme = "ghostwriter"
copyright = "Etienne Dechamps"

[Author]
name = "Etienne Dechamps"
email = "etienne@edechamps.fr"
# TODO: places where this is used (author link) don't expect relative URLs, so this might misbehave depending on baseURL configuration.
profile = "/page/about/"

[Params]
intro = true
headline = "Factual Audio"
description = "The knowledge base for home audio enthusiasts"
shareGooglePlus = false
